#!/bin/bash
export DATA_DIR=/data/arma3
export CONFIG_DIR=/home/steam/arma3

main() {
  # perform pre-install configuration
  initial_checks

  if [[ $DRYRUN = true ]]; then
    echo 'This is a dry county, Son!'
  else
    startup
  fi
}

initial_checks() {
  if [ ! -f $CONFIG_DIR/steamer.txt ]
    then
      do_steamer_config
  fi

  if [[ $BUILD_ENABLED = true ]]; then
    if [[ $FORCEUPDATE = true ]] || [ ! -f $DATA_DIR/dockarmaiii_update_date ]
      then
        do_app_update
    fi

    if [[ $WASTELAND_ENABLED = true ]]; then
      do_wasteland_dl
    fi

    if [[ $OVERWATCH_ENABLED = true ]]; then
      do_ace_dl
      do_cba_dl
      do_overwatch_dl
    fi
  fi
}

fs_check() {
  if [ ! -f $1 ]
    then
      COUNTZERO=0
      echo "waiting on $1 to be writable"
      echo 'success' |tee $1 || true
      FS_CHECK=$(cat $1 ) || FS_CHECK=0
      while [ ! $FS_CHECK = 'success' ]
      do
        sleep 3
        echo 'success' |tee $1 || true
        FS_CHECK=$(cat $1 ) || FS_CHECK=0
        echo "count $COUNTZERO"
        (( COUNTZERO++ ))
      done
      echo "File system check of $1 was $FS_CHECK"
      rm $1
  else
    echo "$1 exists already"
  fi
}

export_startup_vars() {
  # perform post-install configuration

  # set the server aspect (--server/--client)
  if [[ ${HEADLESS_CLIENT} ]]
    then
      export ASPECT="-client"
  else
      export ASPECT="-server"
  fi

  if [[ $MODS ]]
    then
      # format the MODS string to escape ;
      export MODS=$(echo "$MODS"  | sed 's|;|\\;|g')
      export MODSTRING="-mod=$MODS"
  else
      export MODSTRING=""
  fi

  # set the port
  if [[ $PORT ]]
    then
      export PORTSTRING="-port=$PORT"
  else
      export PORTSTRING="-port=2302"
  fi

  # format the SERVERMODS string to escape ;
  if [[ $SERVERMODS ]]
    then
      export SERVERMODS=$(echo "$SERVERMODS"  | sed 's|;|\\;|g')
      export SERVERMODSTRING="-servermod=$SERVERMODS"
  else
      export SERVERMODSTRING=""
  fi

  export CMDSTRING="-netlog $ASPECT -pid=$CONFIG_DIR/arma3server.pid -ranking=$CONFIG_DIR/ranking.log -ip=0.0.0.0 $PORTSTRING -profiles=$CONFIG_DIR/profiles -cfg=$CONFIG_DIR/arma3-server.network.cfg -config=$CONFIG_DIR/arma3-server.server.cfg -bepath=$DATA_DIR/battleye $MODSTRING $SERVERMODSTRING"
}

startup() {
  export_startup_vars

  cd $DATA_DIR
  while [ 1 ]
  do
    echo "./arma3server $CMDSTRING"
    eval ./arma3server $CMDSTRING
    echo restarting
    sleep 3
  done
}

do_app_update() {
  echo 'data install'
  # check to see FS mounts are writable
  sudo mkdir -p $DATA_DIR
  sudo chown steam. $DATA_DIR
  fs_check $DATA_DIR/testfile
  date -I > $DATA_DIR/dockarmaiii_start_data
  cat $DATA_DIR/dockarmaiii_start_data
  mkdir -p $DATA_DIR/arma3
  cd /opt/steamer
  ./steamcmd.sh +runscript $CONFIG_DIR/steamer.txt
  cd $DATA_DIR
  rm -Rf $DATA_DIR/mpmissions
  mkdir -p $CONFIG_DIR/mpmissions
  ln -s $CONFIG_DIR/mpmissions
  rm $DATA_DIR/dockarmaiii_start_data
  date -I > $DATA_DIR/dockarmaiii_update_date
  sudo chown -R steam. $DATA_DIR
}

do_steamer_config() {
  echo 'configuration'
  sudo mkdir -p $CONFIG_DIR
  sudo chown steam. $CONFIG_DIR
  fs_check $CONFIG_DIR/testfile
  date -I > $CONFIG_DIR/dockarmaiii_start_config
  cat $CONFIG_DIR/dockarmaiii_start_config

  cd $CONFIG_DIR
  DATA_DIR=$DATA_DIR envsubst < /assets/steamer.txt > $CONFIG_DIR/steamer.txt

  # if these aren't present the server will segfault/coredump
  mkdir -p "$CONFIG_DIR/.local/share/Arma 3"
  mkdir -p "$CONFIG_DIR/.local/share/Arma 3 - Other Profiles"
  mkdir -p $CONFIG_DIR/profiles

  cp /assets/arma3-server.server.cfg ./
  cp /assets/arma3-server.network.cfg ./

  sed -i  "s/^headlessClients.*/headlessClients[]=\{\"$CLIENT_IP\", \"$CLIENT_IP2\", \"$CLIENT_IP3\", \"$CLIENT_IP4\", \"$CLIENT_IP5\", \"$CLIENT_IP6\" \};/" ./arma3-server.server.cfg
  sed -i  "s/^localClient.*/localClient[]=\{\"$CLIENT_IP\", \"$CLIENT_IP2\", \"$CLIENT_IP3\", \"$CLIENT_IP4\", \"$CLIENT_IP5\", \"$CLIENT_IP6\" \};/" ./arma3-server.server.cfg
  sed -i  "s/^passwordAdmin.*/passwordAdmin = \"$ADMIN_PASSWORD\";/" ./arma3-server.server.cfg
  sed -i  "s/^hostname.*/hostname = \"$HOSTNAME\";/" ./arma3-server.server.cfg
  sed -i  "s/^maxPlayers.*/maxPlayers = \"$MAX_PLAYERS\";/" ./arma3-server.server.cfg

  if [[ $GAME_PASSWORD ]]
    then
      echo "password = \"$GAME_PASSWORD\";" >> ./arma3-server.server.cfg
  fi

  sudo chown -R steam. $CONFIG_DIR
  rm $CONFIG_DIR/dockarmaiii_start_config
  date -I > $CONFIG_DIR/dockarmaiii_update_config
}

do_wasteland_dl() {
  if [ ! -f $DATA_DIR/.wasteland.dl ]
    then
      echo "WASTELAND_DL"
      cd $CONFIG_DIR/mpmissions
      wget -c -q https://github.com/Thalhalla/ArmA3_Wasteland.Altis/raw/dev/release/ArmA3_Wasteland.Altis.pbo
      date -I > $DATA_DIR/.wasteland.dl
  fi
}

do_overwatch_dl() {
  if [ ! -f $DATA_DIR/.overwatch.dl ]
    then
      echo "OVERWATCH_DL ${OVERTHROW_VERSION:=0.7.5.1}"
      TMP=$(mktemp -d)
      cd $TMP
      wget -cq https://github.com/ArmaOverthrow/Overthrow/archive/$OVERTHROW_VERSION.zip
      unzip $OVERTHROW_VERSION.zip
      mkdir -p "$DATA_DIR/mods"
      mv Overthrow-$OVERTHROW_VERSION  "$DATA_DIR/mods/@Overthrow"
      cd
      rm -Rf $TMP
      date -I > $DATA_DIR/.overwatch.dl
  fi
}

do_cba_dl() {
  if [ ! -f $DATA_DIR/.cba.dl ]
    then
      echo "CBA_DL ${CBA_VERSION:=3.4.0.170627}"
      CBA_FILE=CBA_A3-$CBA_VERSION
      TMP=$(mktemp -d)
      cd $TMP
      wget -cq https://github.com/CBATeam/CBA_A3/archive/v$CBA_VERSION.zip
      unzip $CBA_FILE.zip
      rm $CBA_FILE.zip
      mkdir -p "$DATA_DIR/mods"
      mv CBA_A3-3.4.0.170627 "$DATA_DIR/mods/@CBA_A3"
      cd
      rm -Rf $TMP
      date -I > $DATA_DIR/.cba.dl
  fi
}

do_ace_dl() {
  if [ ! -f $DATA_DIR/.ace.dl ]
    then
      echo "ACE_DL ${ACE_VERSION:=3.10.1}"
      ACE_FILE=ace3_$ACE_VERSION.zip
      TMP=$(mktemp -d)
      cd $TMP
      wget -cq https://github.com/acemod/ACE3/releases/download/v$ACE_VERSION/$ACE_FILE
      unzip $ACE_FILE
      mkdir -p "$DATA_DIR/mods"
      mv '@ace' "$DATA_DIR/mods/@ace"
      cd
      rm -Rf $TMP
      date -I > $DATA_DIR/.ace.dl
  fi
}

main "$@"
